Repository hmcts/ccpay-refunds-app, pull requests merged in 2023-08, with the labels that each got.

#393 PAY-6392: Refunds API
  .github/workflows/ci.yml
  Dockerfile
  build.gradle
  charts/ccpay-refunds-api/values.preview.template.yaml
  config/owasp/suppressions.xml
  cve-resolution-strategy.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/uk/gov/hmcts/reform/refunds/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/refunds/config/security/SpringSecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/refunds/controllers/RefundsActionController.java
  src/main/java/uk/gov/hmcts/reform/refunds/controllers/RefundsController.java
  src/main/java/uk/gov/hmcts/reform/refunds/services/NotificationServiceImpl.java
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-refunds-api-pr-393

#396 Pay 6392
  audit.json
  build.gradle
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-refunds-api-pr-396

#398 PAY-6443: Add CVE fix and suppression
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-refunds-api-pr-398

#402 fix attempt PAY_6471
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-refunds-api-pr-402

#405 PAY-6510: Nightly build pipeline fixes
  audit.json
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-refunds-api-pr-405
