Repository hmcts/ccpay-refunds-app, pull requests merged in 2023-12, with the labels that each got.

#528 PAY-6717 amend secrets
  build.gradle
  infrastructure/main.tf
Labels: ns:fees-pay, prd:ccpay, add-or-update, rel:ccpay-refunds-api-pr-528

#532 PAY-6746 logback
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-refunds-api-pr-532

#533 PAY-6756 owasp upgrade
  build.gradle
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-refunds-api-pr-533

#534 PAY-6659-decommission v11 database
  charts/ccpay-refunds-api/Chart.yaml
  charts/ccpay-refunds-api/values.yaml
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:ccpay, destroy, rel:ccpay-refunds-api-pr-534

#535 PAY-6659-decommission v11 database
  charts/ccpay-refunds-api/Chart.yaml
  charts/ccpay-refunds-api/values.aat.template.yaml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-refunds-api-pr-535
